Intern optional registry
Qualytics/loader-kafka pull request #2
Opened 2021-01-21 17:20 UTC by sophiekeller

Three things to note:

1) When running a Meltano elt with loader-kafka, we were getting an error on line 202 that parse_args was missing an argument. We just sent an empty array through to get past this, but wanted to flag in case you want to drop that. The error is commented in the code. 

2) It looks like the master version only creates the records topic dynamically (not state). We changed it so that upon a schema message, topics are potentially created for records, state, and (if raw json) schema. 

3) We noticed when the message's stream name contain a hyphen (for ex, "qualytics-stream", an exception is thrown when the avro schema is loaded (line 154). Underscores don't cause this problem, only hyphens.

2021-01-22 22:30 UTC, ets commented
Thanks for the notes.  Yes AVRO has naming restrictions and hyphens are disallowed for keys which is annoying. See line 76 where we declare the AVRO pattern of allowed characters. field alias is used to capture.  But I can't think of why we'd have stream name used as a key anywhere...so I'll have to take a look.

2021-01-22 22:48 UTC, ets requested changes
Looking good but let's add a test or two.  Look at test_loader.test_parse_and_persist_logic  use that as an example to write tests that verify we create & use the expected topics based upon the configuration.  IOW - when we don't include a registry URL that we create a schema topic and vice versa.

2021-01-22 22:48 UTC, ets commented on loader_kafka/__init__.py
> +    args = utils.parse_args([]) #added argument to avoid TypeError: parse_args() missing 1 required positional argument: 'required_config_keys'
This is correct.  We don't want utils to enforce required fields so we should pass an empty array.  Instead we enforce/validate using voluptous in Configuration

2021-01-22 22:48 UTC, ets commented on loader_kafka/__init__.py
> +    return config["topic_prefix"] + ".records"
This needs to include stream name - so let's collapse into one method used for raw and registry.   
The reason why is that we could be processing multiple different streams and we want to maintain one stream per topic.

2021-01-22 22:48 UTC, ets commented on loader_kafka/__init__.py
>      return config["topic_prefix"] + ".state"
This is correct because state messages are NOT stream specific. So we don't use stream name here.

2021-01-22 22:48 UTC, ets commented on loader_kafka/__init__.py
> +    return config["topic_prefix"] + ".schema"
We need stream name here.  All schema messages will have the same schema so we could put them in the same topic - but it'll be more convenient to have a sibling topic of "records" that holds that specific stream's schema.

2021-01-26 16:19 UTC, sophiekeller commented
We made the requested changes to the schema/record topic naming and topic creation tests. Let us know if there's anything we should alter.

2021-01-27 20:28 UTC, merged